---
# tasks file for jenkins
- name: install java
  yum:
    name: java
    state: present

- name: curl jenkins
  shell:
    cmd: curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo

- name: curl jenkins
  shell:
    cmd: sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins
  yum:
    name: jenkins
    state: present

- name: start jenkins
  service:
    name: jenkins
    state: started
