---
# tasks file for apache
- name: Install apache
  yum:
    name: httpd
    state: present

- name: change port for apache
  template:
    src: httpdgib.j2
    dest: /etc/httpd/conf/httpd.conf
    backup: yes
  notify: restart httpd

- name: start httpd
  service:
    name: httpd
    state: started
