---
- hosts:  localhost
  become:  yes

  vars:
    my_new_port:  80

  tasks:
  - name:    Install apache
    yum:
      name:    httpd
      state:    present
  - name:    change port for apache
    template:
      src:  /home/vagrant/playbook_apache_config/httpdgib.j2
      dest:  /etc/httpd/conf/httpd.conf
      backup:  yes
    notify:  restart httpd
  - name:  start httpd
    service:
      name:  httpd
      state:  started

  handlers:
  - name: restart httpd
    service:
      name:  httpd
      state: restarted
