---
- hosts:  localhost
  become:  yes
  tasks:
  - name:    Install apache
    yum:
      name:    httpd
      state:    present
  - name:    change port for apache
    lineinfile:
      path:    /etc/httpd/conf/httpd.conf
      regexp:  '^Listen '
      insertafter:  '^#Listen '
      line:  Listen 81
  - name:  start httpd
    service:
      name:  httpd
      state:  started
  - name:  start httpd
    service:
      name:  httpd
      state:  restarted
